# Makefile for SpectreMeltdownTracker

# Variables
SCRIPT_FILE := ./spectre-meltdown-checker.sh

# Targets
all: give_execute_permission

give_execute_permission:
	chmod +x $(SCRIPT_FILE)
	@echo "Execute permission given to $(SCRIPT_FILE)"

# PHONY targets (targets that are not actual files)
.PHONY: all give_execute_permission
